---
title: "🇨🇦 Canadian ATI Archive"
output: 
  html_fragment:
    toc: FALSE
---

### Accessing government information can be tricky. We want to make it easier.

<font size = 4> Journalists, academics, lawyers, and members of the public file tens of thousands of requests for information from the Canadian Government every year. But previously filed Access to Information (ATI) requests aren't made public by default. Demand for government information in Canada far exceeds what is accessible.

That's why we built the Canadian ATI Archive. Civic technologists have an important role to play in envisioning ways to improve how governments engage with residents. 

This dashboard, sponsored by the [Centre for Access to Information and Justice](https://www.uwinnipeg.ca/caij/), allows you to easily search for previously completed ATI requests from the Canadian Federal Government and locate documents currently included in the Canadian ATI Archive. It was created by [Jamie Duncan](https://jamieduncan.me), [Alex Luscombe](https://alexluscombe.ca), and [Lucas Cherkewski](https://github.com/lchski/gc-ati-summaries-data) with support from [Kevin Walby](https://www.uwinnipeg.ca/criminal-justice/faculty-staff/kevin-walby.html) and [Sean Boots](https://sboots.ca/). Files are stored on the Internet Archive and can be explored using Google's Pinpoint tool for investigative journalists.

Spot an error? Have a suggestion? Files to contribute? Just want to chat? [Get in touch](mailto:caij.winnipeg@gmail.com) with us!






